"""added user metadata

Revision ID: 105cc84c2559
Revises: e137d445201a
Create Date: 2023-08-13 18:06:00.175803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105cc84c2559'
down_revision = 'e137d445201a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
